version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch
    restart: on-failure
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
      - NODE_OPTIONS="--max-old-space-size=200"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    command:
    - sh
    - -c
    - "bin/elasticsearch-plugin install analysis-icu;
        /usr/local/bin/docker-entrypoint.sh elasticsearch
        -Ecluster.initial_master_nodes=elasticsearch
        -Enode.name=elasticsearch
        -Ehttp.cors.enabled=true
        -Ehttp.cors.allow-origin=*"
    networks:
      - elastic
#    ports:
#      - 9200:9200
#      - 9300:9300

    volumes:
      - type: volume
        source: logs
        target: /var/log
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    depends_on:
      - elasticsearch
#    ports:
#      - 5601:5601
    restart: always
    networks:
      - elastic
    links:
        - elasticsearch

  nginx-kibana:
    image: beevelop/nginx-basic-auth
    container_name: nginx-kibana-auth
    depends_on:
      - kibana
    environment:
      - HTPASSWD=kibana:{PLAIN}kibana_password
      - FORWARD_PORT=5601
    networks:
      - elastic
    ports:
      - 80:80
    links:
      - kibana:web

  nginx-es:
    image: beevelop/nginx-basic-auth
    container_name: nginx-es-auth
    depends_on:
      - elasticsearch
    environment:
      - HTPASSWD=api:{PLAIN}api_password
      - FORWARD_PORT=9200
    networks:
      - elastic
    ports:
      - 9200:80
    links:
      - elasticsearch:web

volumes:
  esdata:
  logs:

networks:
  elastic:
